version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_zeepwifi
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: zeepwifiDB
      MYSQL_USER: zeepuser
      MYSQL_PASSWORD: Ap0ll0@123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
